mock_data = {
  "info": {
    "count": 826,
    "pages": 42,
    "next": "https://test-rick_and_morty.com/character/?page=2",
    "prev": None
  },
  "results": [
    {
      "id": 1,
      "name": "Rick Sanchez",
      "status": "Alive",
      "species": "Human",
      "type": "",
      "gender": "Male",
      "origin": {
        "name": "Earth (C-137)",
        "url": "https://test-rick_and_morty.com/location/1"
      },
      "location": {
        "name": "Citadel of Ricks",
        "url": "https://test-rick_and_morty.com/location/3"
      },
      "image": "https://test-rick_and_morty.com/character/avatar/1.jpeg",
      "episode": [
        "https://test-rick_and_morty.com/episode/1",
        "https://test-rick_and_morty.com/episode/2",
        "https://test-rick_and_morty.com/episode/3",
        "https://test-rick_and_morty.com/episode/4",
        "https://test-rick_and_morty.com/episode/5",
        "https://test-rick_and_morty.com/episode/6",
        "https://test-rick_and_morty.com/episode/7",
        "https://test-rick_and_morty.com/episode/8",
        "https://test-rick_and_morty.com/episode/9",
        "https://test-rick_and_morty.com/episode/10",
        "https://test-rick_and_morty.com/episode/11",
        "https://test-rick_and_morty.com/episode/12",
        "https://test-rick_and_morty.com/episode/13",
        "https://test-rick_and_morty.com/episode/14",
        "https://test-rick_and_morty.com/episode/15",
        "https://test-rick_and_morty.com/episode/16",
        "https://test-rick_and_morty.com/episode/17",
        "https://test-rick_and_morty.com/episode/18",
        "https://test-rick_and_morty.com/episode/19",
        "https://test-rick_and_morty.com/episode/20",
        "https://test-rick_and_morty.com/episode/21",
        "https://test-rick_and_morty.com/episode/22",
        "https://test-rick_and_morty.com/episode/23",
        "https://test-rick_and_morty.com/episode/24",
        "https://test-rick_and_morty.com/episode/25",
        "https://test-rick_and_morty.com/episode/26",
        "https://test-rick_and_morty.com/episode/27",
        "https://test-rick_and_morty.com/episode/28",
        "https://test-rick_and_morty.com/episode/29",
        "https://test-rick_and_morty.com/episode/30",
        "https://test-rick_and_morty.com/episode/31",
        "https://test-rick_and_morty.com/episode/32",
        "https://test-rick_and_morty.com/episode/33",
        "https://test-rick_and_morty.com/episode/34",
        "https://test-rick_and_morty.com/episode/35",
        "https://test-rick_and_morty.com/episode/36",
        "https://test-rick_and_morty.com/episode/37",
        "https://test-rick_and_morty.com/episode/38",
        "https://test-rick_and_morty.com/episode/39",
        "https://test-rick_and_morty.com/episode/40",
        "https://test-rick_and_morty.com/episode/41",
        "https://test-rick_and_morty.com/episode/42",
        "https://test-rick_and_morty.com/episode/43",
        "https://test-rick_and_morty.com/episode/44",
        "https://test-rick_and_morty.com/episode/45",
        "https://test-rick_and_morty.com/episode/46",
        "https://test-rick_and_morty.com/episode/47",
        "https://test-rick_and_morty.com/episode/48",
        "https://test-rick_and_morty.com/episode/49",
        "https://test-rick_and_morty.com/episode/50",
        "https://test-rick_and_morty.com/episode/51"
      ],
      "url": "https://test-rick_and_morty.com/character/1",
      "created": "2017-11-04T18:48:46.250Z"
    },
    {
      "id": 2,
      "name": "Morty Smith",
      "status": "Alive",
      "species": "Human",
      "type": "",
      "gender": "Male",
      "origin": {
        "name": "unknown",
        "url": ""
      },
      "location": {
        "name": "Citadel of Ricks",
        "url": "https://test-rick_and_morty.com/location/3"
      },
      "image": "https://test-rick_and_morty.com/character/avatar/2.jpeg",
      "episode": [
        "https://test-rick_and_morty.com/episode/1",
        "https://test-rick_and_morty.com/episode/2",
        "https://test-rick_and_morty.com/episode/3",
        "https://test-rick_and_morty.com/episode/4",
        "https://test-rick_and_morty.com/episode/5",
        "https://test-rick_and_morty.com/episode/6",
        "https://test-rick_and_morty.com/episode/7",
        "https://test-rick_and_morty.com/episode/8",
        "https://test-rick_and_morty.com/episode/9",
        "https://test-rick_and_morty.com/episode/10",
        "https://test-rick_and_morty.com/episode/11",
        "https://test-rick_and_morty.com/episode/12",
        "https://test-rick_and_morty.com/episode/13",
        "https://test-rick_and_morty.com/episode/14",
        "https://test-rick_and_morty.com/episode/15",
        "https://test-rick_and_morty.com/episode/16",
        "https://test-rick_and_morty.com/episode/17",
        "https://test-rick_and_morty.com/episode/18",
        "https://test-rick_and_morty.com/episode/19",
        "https://test-rick_and_morty.com/episode/20",
        "https://test-rick_and_morty.com/episode/21",
        "https://test-rick_and_morty.com/episode/22",
        "https://test-rick_and_morty.com/episode/23",
        "https://test-rick_and_morty.com/episode/24",
        "https://test-rick_and_morty.com/episode/25",
        "https://test-rick_and_morty.com/episode/26",
        "https://test-rick_and_morty.com/episode/27",
        "https://test-rick_and_morty.com/episode/28",
        "https://test-rick_and_morty.com/episode/29",
        "https://test-rick_and_morty.com/episode/30",
        "https://test-rick_and_morty.com/episode/31",
        "https://test-rick_and_morty.com/episode/32",
        "https://test-rick_and_morty.com/episode/33",
        "https://test-rick_and_morty.com/episode/34",
        "https://test-rick_and_morty.com/episode/35",
        "https://test-rick_and_morty.com/episode/36",
        "https://test-rick_and_morty.com/episode/37",
        "https://test-rick_and_morty.com/episode/38",
        "https://test-rick_and_morty.com/episode/39",
        "https://test-rick_and_morty.com/episode/40",
        "https://test-rick_and_morty.com/episode/41",
        "https://test-rick_and_morty.com/episode/42",
        "https://test-rick_and_morty.com/episode/43",
        "https://test-rick_and_morty.com/episode/44",
        "https://test-rick_and_morty.com/episode/45",
        "https://test-rick_and_morty.com/episode/46",
        "https://test-rick_and_morty.com/episode/47",
        "https://test-rick_and_morty.com/episode/48",
        "https://test-rick_and_morty.com/episode/49",
        "https://test-rick_and_morty.com/episode/50",
        "https://test-rick_and_morty.com/episode/51"
      ],
      "url": "https://test-rick_and_morty.com/character/2",
      "created": "2017-11-04T18:50:21.651Z"
    },
    {
      "id": 3,
      "name": "Summer Smith",
      "status": "Alive",
      "species": "Human",
      "type": "",
      "gender": "Female",
      "origin": {
        "name": "Earth (Replacement Dimension)",
        "url": "https://test-rick_and_morty.com/location/20"
      },
      "location": {
        "name": "Earth (Replacement Dimension)",
        "url": "https://test-rick_and_morty.com/location/20"
      },
      "image": "https://test-rick_and_morty.com/character/avatar/3.jpeg",
      "episode": [
        "https://test-rick_and_morty.com/episode/6",
        "https://test-rick_and_morty.com/episode/7",
        "https://test-rick_and_morty.com/episode/8",
        "https://test-rick_and_morty.com/episode/9",
        "https://test-rick_and_morty.com/episode/10",
        "https://test-rick_and_morty.com/episode/11",
        "https://test-rick_and_morty.com/episode/12",
        "https://test-rick_and_morty.com/episode/14",
        "https://test-rick_and_morty.com/episode/15",
        "https://test-rick_and_morty.com/episode/16",
        "https://test-rick_and_morty.com/episode/17",
        "https://test-rick_and_morty.com/episode/18",
        "https://test-rick_and_morty.com/episode/19",
        "https://test-rick_and_morty.com/episode/20",
        "https://test-rick_and_morty.com/episode/21",
        "https://test-rick_and_morty.com/episode/22",
        "https://test-rick_and_morty.com/episode/23",
        "https://test-rick_and_morty.com/episode/24",
        "https://test-rick_and_morty.com/episode/25",
        "https://test-rick_and_morty.com/episode/26",
        "https://test-rick_and_morty.com/episode/27",
        "https://test-rick_and_morty.com/episode/29",
        "https://test-rick_and_morty.com/episode/30",
        "https://test-rick_and_morty.com/episode/31",
        "https://test-rick_and_morty.com/episode/32",
        "https://test-rick_and_morty.com/episode/33",
        "https://test-rick_and_morty.com/episode/34",
        "https://test-rick_and_morty.com/episode/35",
        "https://test-rick_and_morty.com/episode/36",
        "https://test-rick_and_morty.com/episode/38",
        "https://test-rick_and_morty.com/episode/39",
        "https://test-rick_and_morty.com/episode/40",
        "https://test-rick_and_morty.com/episode/41",
        "https://test-rick_and_morty.com/episode/42",
        "https://test-rick_and_morty.com/episode/43",
        "https://test-rick_and_morty.com/episode/44",
        "https://test-rick_and_morty.com/episode/45",
        "https://test-rick_and_morty.com/episode/46",
        "https://test-rick_and_morty.com/episode/47",
        "https://test-rick_and_morty.com/episode/48",
        "https://test-rick_and_morty.com/episode/49",
        "https://test-rick_and_morty.com/episode/51"
      ],
      "url": "https://test-rick_and_morty.com/character/3",
      "created": "2017-11-04T19:09:56.428Z"
    }
  ]
}